#!/bin/bash

set -xeu

if [[ "$1" = install ]]
then
    rustup install 1.15.1
    rustup override set 1.15.1
    cargo build --release
elif [[ "$1" = test ]]
then
    rustc --version
    cargo test --release
else
    exit 1
fi
