#!/bin/bash
# Used for continuous integration (CI).

set -eux

if [[ "$1" = install ]]
then
    rustup install 1.42.0
    rustup override set 1.42.0
    cargo build --release
elif [[ "$1" = test ]]
then
    rustc --version
    cargo test --release
else
    exit 1
fi
